# Generated by Django 3.1.5 on 2021-02-06 16:21

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_presentation_project_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
