# Generated by Django 3.1.5 on 2021-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210206_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications'),
        ),
    ]
