# Generated by Django 3.1.5 on 2021-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publication_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='authors',
        ),
        migrations.AddField(
            model_name='presentation',
            name='type',
            field=models.CharField(choices=[('guest_lecture', 'Guest lecture'), ('conference', 'Conference presentation'), ('other', 'Other')], default='guest_lecture', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
