# Generated by Django 3.1.5 on 2021-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210206_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='presented_remotely',
            field=models.BooleanField(default=False),
        ),
    ]
