# Generated by Django 3.2 on 2021-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210428_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespace',
            name='temp_source_id',
            field=models.IntegerField(blank=True, help_text='Only used when importing data', null=True),
        ),
    ]
