# Generated by Django 3.2 on 2021-04-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_referencespace_temp_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Nature'), (2, 'Connector layers'), (3, 'Transport'), (4, 'Potential sites'), (5, 'Context')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='referencespace',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='core.document'),
        ),
    ]
