# Generated by Django 3.2 on 2021-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210428_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
