# Generated by Django 3.2 on 2021-04-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_document_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
