# Generated by Django 3.2 on 2021-05-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_document_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Animal-friendly'), (2, 'Tolerances/sites'), (3, 'Growth features'), (4, 'Other')], db_index=True, default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='species',
            name='features',
            field=models.ManyToManyField(blank=True, to='core.SpeciesFeatures'),
        ),
    ]
