# Generated by Django 3.2 on 2021-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210507_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='common_name_af',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='common_name_xh',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
