# Generated by Django 3.2 on 2021-05-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210507_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
