# Generated by Django 3.2 on 2021-05-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210528_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationtype',
            name='slug',
            field=models.SlugField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
