# Generated by Django 3.2 on 2021-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210528_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_html',
            field=models.TextField(blank=True, help_text='Auto-generated - do NOT edit', null=True),
        ),
    ]
