# Generated by Django 3.2 on 2021-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_redlist_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationtype',
            name='reference_spaces',
            field=models.ManyToManyField(blank=True, to='core.ReferenceSpace'),
        ),
    ]
