# Generated by Django 3.2 on 2021-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_reference_spaces_vegetationtype_spaces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencespace',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='species',
            name='vegetation_types',
            field=models.ManyToManyField(blank=True, to='core.VegetationType'),
        ),
    ]
