# Generated by Django 3.2 on 2021-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_species_vegetation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='species', to='core.SpeciesFeatures'),
        ),
    ]
