# Generated by Django 3.2 on 2021-06-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210611_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='content',
            new_name='description',
        ),
    ]
