# Generated by Django 3.2 on 2021-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_content_garden_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='phase_alienremoval',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_assessment',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_birdsinsects',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_landscaping',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_pioneers',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_placemaking',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_specialists',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True),
        ),
    ]
