# Generated by Django 3.2 on 2021-06-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210611_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='core.Organization'),
        ),
    ]
