# Generated by Django 3.2 on 2021-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_garden_organizations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garden',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='photo',
            name='old_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='original',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
