# Generated by Django 3.2.5 on 2021-09-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='color',
            field=models.CharField(blank=True, help_text='See https://htmlcolors.com/color-names for an overview of possible color names', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='meta_data',
            field=models.JSONField(blank=True, help_text='Only to be edited if you know what this does - otherwise, please do not change', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
