# Generated by Django 3.2.5 on 2021-10-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210923_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='redlist',
            options={'verbose_name_plural': 'Redlist'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
