# Generated by Django 3.2.5 on 2021-10-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20211014_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetationtype',
            name='spaces',
            field=models.ManyToManyField(blank=True, limit_choices_to={'source_id': 983172}, to='core.ReferenceSpace'),
        ),
    ]
