# Generated by Django 3.2.5 on 2021-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_vegetationtype_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='include_in_site_analysis',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
