# Generated by Django 3.2.5 on 2021-10-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_document_include_in_site_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenNew',
            fields=[
                ('referencespace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.referencespace')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('original', models.JSONField(blank=True, null=True)),
                ('phase_assessment', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True)),
                ('phase_alienremoval', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True)),
                ('phase_landscaping', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True)),
                ('phase_pioneers', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True)),
                ('phase_birdsinsects', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True)),
                ('phase_specialists', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True)),
                ('phase_placemaking', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True)),
                ('organizations', models.ManyToManyField(blank=True, to='core.Organization')),
            ],
            bases=('core.referencespace',),
        ),
        migrations.DeleteModel(
            name='Corridor',
        ),
    ]
