# Generated by Django 3.2.5 on 2021-10-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20211023_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='g',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.gardennew'),
        ),
    ]
