# Generated by Django 3.2.5 on 2021-10-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_photo_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='garden',
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
    ]
