# Generated by Django 3.2.5 on 2021-10-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20211023_0209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GardenNew',
            new_name='Garden',
        ),
    ]
