# Generated by Django 3.2.5 on 2021-10-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_gardennew_garden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='g',
            new_name='garden',
        ),
    ]
