# Generated by Django 3.2.5 on 2021-10-25 22:46

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_referencespace_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('general_description', models.TextField(blank=True, null=True)),
                ('social_description', models.TextField(blank=True, null=True)),
                ('image', stdimage.models.StdImageField(upload_to='corridors')),
                ('wards', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
