# Generated by Django 3.2.5 on 2021-10-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
