# Generated by Django 3.2.5 on 2021-10-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_organization_part_of_fcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='vegetation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='core.vegetationtype'),
        ),
    ]
