# Generated by Django 3.2.5 on 2021-10-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_garden_vegetation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Existing stepping-stones'), (2, 'Corridor connectors'), (3, 'Transport'), (4, 'Possible stepping-stone sites'), (5, 'Context'), (6, 'Teaching resources'), (7, 'General document repository')], db_index=True, default=0),
        ),
    ]
