# Generated by Django 3.2.5 on 2021-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20211027_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Existing stepping-stones'), (2, 'Corridor connectors'), (3, 'Transport'), (4, 'Possible stepping-stones'), (5, 'Context'), (6, 'Teaching resources'), (7, 'General document repository')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_alienremoval',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Alien removal'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_assessment',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Initial ecological and social assessment'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_birdsinsects',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Planting of bird and insect species'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_landscaping',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Landscaping'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_pioneers',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Planting of pioneer species'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_placemaking',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Placemaking'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='phase_specialists',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Planting of specialist species'),
        ),
    ]
