# Generated by Django 3.2.8 on 2023-02-02 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20220915_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.garden')),
            ],
            options={
                'ordering': ['garden', 'name'],
            },
        ),
    ]
