# Generated by Django 3.2.8 on 2023-02-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_gardenmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gardenmanager',
            old_name='uuid',
            new_name='token',
        ),
        migrations.AddField(
            model_name='gardenmanager',
            name='token_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
